import { NgModule } from '@angular/core';
import { MdDatepickerModule,
         MdRadioModule,
         MdChipsModule,
         MdToolbarModule,
         MdButtonModule,
         MdCardModule,
         MdInputModule,
         MdSnackBarModule,
         MdMenuModule,
         MdSidenavModule,
         MdSelectModule } from '@angular/material';

@NgModule({
  imports: [MdDatepickerModule,
            MdRadioModule,
            MdChipsModule,
            MdToolbarModule,
            MdButtonModule,
            MdCardModule,
            MdInputModule,
            MdSnackBarModule,
            MdMenuModule,
            MdSidenavModule,
            MdSelectModule ],
  exports: [MdDatepickerModule,
            MdRadioModule,
            MdChipsModule,
            MdToolbarModule,
            MdButtonModule,
            MdCardModule,
            MdInputModule,
            MdSnackBarModule,
            MdMenuModule,
            MdSidenavModule,
            MdSelectModule],
})
export class MaterialComponents {}
