import { NgModule } from '@angular/core';
import { MdDatepickerModule,
         MdRadioModule,
         MdChipsModule,
         MdToolbarModule,
         MdButtonModule,
         MdCardModule,
         MdInputModule,
         MdSnackBarModule,
         MdMenuModule,
         MdSidenavModule,
         MdSelectModule,
         MdCheckboxModule } from '@angular/material';

@NgModule({
  imports: [MdDatepickerModule,
            MdRadioModule,
            MdChipsModule,
            MdToolbarModule,
            MdButtonModule,
            MdCardModule,
            MdInputModule,
            MdSnackBarModule,
            MdMenuModule,
            MdSidenavModule,
            MdSelectModule,
            MdCheckboxModule ],
  exports: [MdDatepickerModule,
            MdRadioModule,
            MdChipsModule,
            MdToolbarModule,
            MdButtonModule,
            MdCardModule,
            MdInputModule,
            MdSnackBarModule,
            MdMenuModule,
            MdSidenavModule,
            MdSelectModule,
            MdCheckboxModule],
})
export class MaterialComponents {}